import './globals.scss'
import { Montserrat } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { AnalyticsWrapper } from '@/components/Analytics'
import { Metadata } from 'next'


const font = Montserrat({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  title: 'Rick and Morty wiki',
  description: 'Generated by create next app',
  icons: 'favicon.ico'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={font.className}>
        <Header />
        {children}
        <Footer />
        <AnalyticsWrapper />
      </body>
    </html>
  )
}
